EMPTY_CREATE_QUEUE_ARGUMENT = "Введи название очереди, которую хочешь создать."
EMPTY_JOIN_QUEUE_ARGUMENT = "Введи название очереди, в которую хочешь записаться."
EMPTY_LEAVE_QUEUE_ARGUMENT = "Введи название очереди, из которой хочешь выйти."
EMPTY_DELETE_QUEUE_ARGUMENT = "Введи название очереди, которую хочешь удалить."
EMPTY_PASS_QUEUE_ARGUMENT = "Введи количество людей, которых ты хочешь пропустить"
